### PR TITLE
Upgrade Android version

### LINKED ISSUE #34: Upgrade the Kotlin App to the Latest Android Version
Upgrade the Kotlin App target to the Latest Android Version (min SDK can be 2-3 versions lower).

### PR DESCRIPTION
**Pull request by jsherm-fwdsec**
Upgraded Android version to 33, and migrated to AndroidX. 

This PR closes #34.

### CODE REVIEW

**Comment by jsherm-fwdsec** [comment]
Hey @cpholguera. This seems to be failing checks because the build is failing on the "Sign app APK" step. I believe the keys might be misconfigured, because it builds fine in my fork: https://github.com/jsherm-fwdsec/MASTG-Hacking-Playground/pull/2

**Comment by cpholguera** [comment]
Hi @jsherm-fwdsec, thanks for letting me know. When I merged your previous PR the Action was successful, so I assumed that the keys config was right. Please take a look here:

https://github.com/OWASP/MASTG-Hacking-Playground/actions/runs/3040311391

What do you think?

**Review by cpholguera — COMMENTED** [review]
If possible, could you please remove and gitignore the whole ".idea" folder?

**Comment by jsherm-fwdsec** [comment]
Yeah it's really odd behaviour if the keys weren't purposely modified but I can't think of any other reason why. Can you possibly try resetting the keys? Check this out: https://github.com/r0adkll/sign-android-release/issues/61

**Review by cpholguera — APPROVED** [review]
This is great @jsherm-fwdsec, I'll merge and we'll see if the signing works well from master. Thank you very much!

**Pull request merged**
